// <auto-generated />
using BisPlatform.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BisPlatform.Data.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20190506031218_init15")]
    partial class init15
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BisPlatform.Data.Entity.Platform.Test2Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("BIM")
                        .HasMaxLength(12);

                    b.Property<float>("Height")
                        .HasMaxLength(12);

                    b.Property<int>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("xiaoma2");
                });

            modelBuilder.Entity("BisPlatform.Data.Entity.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("testtw");

                    b.HasKey("Id");

                    b.ToTable("xiaoma");
                });

            modelBuilder.Entity("BisPlatform.Data.Entity.Platform.Test2Entity", b =>
                {
                    b.HasOne("BisPlatform.Data.Entity.TestEntity", "testEntity")
                        .WithOne("test2Entity")
                        .HasForeignKey("BisPlatform.Data.Entity.Platform.Test2Entity", "TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
